language: php

php:
  - 7.0

matrix:
  fast_finish: true
  
sudo: false

install:
  - travis_retry composer self-update
  - travis_wait composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit

